### ISSUE TITLE
Base project does not compile

### ISSUE THREAD

**Issue by ianhellstrom** [StaticMania/roxo-eleventy#13]
When I `git clone` and run `npm install` in the directory, I see the following:

```
$HOME/.npm/_npx/755986f37193a6d8/node_modules/run/run.js:127
        if (minimatch(file, pattern)) {
            ^

TypeError: minimatch is not a function
    at $HOME/.npm/_npx/755986f37193a6d8/node_modules/run/run.js:127:13
    at Array.forEach (<anonymous>)
    at parseFolder ($HOME/.npm/_npx/755986f37193a6d8/node_modules/run/run.js:113:9)
    at Object.<anonymous> ($HOME/.npm/_npx/755986f37193a6d8/node_modules/run/run.js:63:12)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at require (node:internal/modules/helpers:121:18)
```

This is with 11ty v2.

**Comment by davymartinez** [comment]
Running `npm run dev` instead of `npx run dev` should fix this.
